/**
 * Test IDs for components
 */
export const componentTestIds = {
    gameRatingBox: {
        wrapper: 'gameRatingBox.wrapper',
    },
    homeAuthored: {
        panel: 'homeAuthored.panel',
        row: (gameId: string) => `homeAuthored.row.${gameId}`,
        voteBadge: 'homeAuthored.voteBadge',
    },
    catalog: {
        panel: 'catalog.panel',
        card: (gameId: string) => `catalogCard.${gameId}`,
        loadMore: 'catalog.loadMore',
        resultCount: 'catalog.resultCount',
        empty: 'catalog.empty',
        reset: 'catalog.reset',
        activeFilters: 'catalog.activeFilters',
        query: 'catalog.query',
    },
    calendar: {
        panel: 'calendar.panel',
        summary: 'calendar.summary',
        filters: 'calendar.filters',
        query: 'calendar.query',
        viewSwitch: 'calendar.viewSwitch',
        view: (view: string) => `calendar.view.${view}`,
        resultCount: 'calendar.resultCount',
        reset: 'calendar.reset',
        empty: 'calendar.empty',
        loadMore: 'calendar.loadMore',
        addEvent: 'calendar.addEvent',
    },
    carousel: {
        leftButton: 'carouselLeftButton',
        rightButton: 'carouselRightButton',
        items: 'carouselItems',
        item: (offset: number) => `carouselItem${offset}`,
    },
    search: {
        panel: 'search.panel',
        tabs: 'search.tabs',
        resultCount: 'search.resultCount',
        empty: 'search.empty',
        tooShort: 'search.tooShort',
        suggestion: 'search.suggestion',
        userCard: (userId: string) => `search.userCard.${userId}`,
        eventList: 'search.eventList',
        headerResults: 'search.headerResults',
        headerGroup: (kind: string) => `search.headerGroup.${kind}`,
        headerShowAll: (kind: string) => `search.headerShowAll.${kind}`,
        // One page for every kind of result: the type is a filter chip, the
        // counts sit on the chips, and the rest of each kind is collapsed.
        query: 'search.query',
        querySummary: 'search.querySummary',
        clearQuery: 'search.clearQuery',
        typeChip: (type: string) => `search.typeChip.${type}`,
        bestMatches: 'search.bestMatches',
        bestMatch: (type: string, index: number) => `search.bestMatch.${type}.${index}`,
        sectionBar: (type: string) => `search.sectionBar.${type}`,
        section: (type: string) => `search.section.${type}`,
        showAll: (type: string) => `search.showAll.${type}`,
        collapse: (type: string) => `search.collapse.${type}`,
        gameRow: (gameId: string) => `search.gameRow.${gameId}`,
        personRow: (userId: string) => `search.personRow.${userId}`,
        eventRow: (eventId: string) => `search.eventRow.${eventId}`,
        groupRow: (groupId: string) => `search.groupRow.${groupId}`,
        matchReason: (id: string) => `search.matchReason.${id}`,
        notRated: 'search.notRated',
        duplicateBadge: (eventId: string) => `search.duplicateBadge.${eventId}`,
        timeFilter: 'search.timeFilter',
        timeOption: (filter: string) => `search.timeOption.${filter}`,
        range: 'search.range',
        emptyType: (type: string) => `search.emptyType.${type}`,
        emptyLink: (type: string) => `search.emptyLink.${type}`,
        typeEmpty: (type: string) => `search.typeEmpty.${type}`,
        otherTypes: 'search.otherTypes',
        // The games section brings the catalog's facets and rankings along.
        gamesFilterToggle: 'search.gamesFilterToggle',
        gamesFilterPanel: 'search.gamesFilterPanel',
        gamesOrder: 'search.gamesOrder',
        gamesPreset: (key: string) => `search.gamesPreset.${key}`,
        gamesActiveFilter: (key: string) => `search.gamesActiveFilter.${key}`,
    },
}
