export const darkTheme = {
    background: '#272727',
    backgroundLight: '#2F2F2F',
    backgroundHover: '#383838',
    backgroundControl: '#3F3F3F',
    backgroundAlmostNearWhite: '#E0E0E0',
    backgroundAlmostNearWhite2: '#E7E7E7',
    backgroundNearWhite: '#EFEFEF',
    backgroundWhite: '#f5f5f5',
    backgroundRealWhite: '#fff',
    text: '#C0C0C0',
    textLighter: '#AFAFAF',
    textLight: '#F0F0F0',
    textDark: '#999',
    textGreen: '#6dc8b7',
    textGreenDark: '#00a0b0',
    textOnLight: '#5f5f5f',
    textOnLightLighter: '#7f7f7f',
    textOnLightDark: '#333',
    red: '#BD2430',
    redLight: '#CC333F',
    ratingMediocre: '#757575',
    ratingGreat: '#BD2430',
    ratingAverage: '#6dc8b7',
    ratingNotRated: '#CCC',
}
