#!/usr/bin/env bash
#
# csld-backup-setup.sh — One-shot bootstrap for the ČSLD git-based backup.
#
# Installs deps, clones the backup repo, configures git identity for the bot,
# installs the backup script under /usr/local/bin, registers cron, and runs
# the first backup immediately to prove the wiring works end-to-end.
#
# Idempotent — safe to re-run. Re-running will:
#   - re-pull (no-op if up-to-date)
#   - re-install the script (overwrites)
#   - re-register the cron job (overwrites)
#   - NOT re-run the backup (set RUN_BACKUP=1 to force)
#
# Run as root or with sudo. Required env (or will prompt):
#   GITHUB_REPO     — full HTTPS clone URL of the backup repo
#                     default: https://github.com/balhar-jakub/larpova-databaze-backup.git
#   BACKUP_REPO_DIR — local checkout path
#                     default: /opt/csld-backup
#
# Assumes `gh auth` is already set up (otherwise `git push` will fail).

set -euo pipefail

GITHUB_REPO="${GITHUB_REPO:-https://github.com/balhar-jakub/larpova-databaze-backup.git}"
BACKUP_REPO_DIR="${BACKUP_REPO_DIR:-/opt/csld-backup}"

# Where this script lives — used to find the backup script it should install.
SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

log() { printf '[%s] %s\n' "$(date -u +%FT%TZ)" "$*"; }
die() { log "ERROR: $*"; exit 1; }

[ "$(id -u)" -eq 0 ] || die "This script must be run as root (use sudo)."

# ── 1. Install system deps ────────────────────────────────────────────────────

log "Installing system dependencies (git, rsync, postgresql-client)"

if command -v apt-get >/dev/null 2>&1; then
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -qq
  apt-get install -y --no-install-recommends git rsync postgresql-client ca-certificates
elif command -v dnf >/dev/null 2>&1; then
  dnf install -y git rsync postgresql
elif command -v yum >/dev/null 2>&1; then
  yum install -y git rsync postgresql
else
  die "Unsupported package manager. Install git, rsync, and postgresql-client manually."
fi

command -v git >/dev/null     || die "git still missing after install"
command -v rsync >/dev/null   || die "rsync still missing after install"
command -v pg_dump >/dev/null || die "pg_dump still missing after install"

# ── 2. Clone the backup repo ──────────────────────────────────────────────────

if [ -d "$BACKUP_REPO_DIR/.git" ]; then
  log "Backup repo already cloned at $BACKUP_REPO_DIR — skipping clone"
else
  log "Cloning $GITHUB_REPO → $BACKUP_REPO_DIR"
  mkdir -p "$(dirname "$BACKUP_REPO_DIR")"
  git clone "$GITHUB_REPO" "$BACKUP_REPO_DIR"
fi

cd "$BACKUP_REPO_DIR"

# Configure bot identity (scoped to this repo only).
git config user.name  "csld-backup-bot"
git config user.email "backup@larpovadatabaze.cz"

# Ensure the expected directory layout exists (idempotent).
mkdir -p db files db/history
[ -f db/.gitkeep ]    || { touch db/.gitkeep;    git add db/.gitkeep; }
[ -f files/.gitkeep ] || { touch files/.gitkeep; git add files/.gitkeep; }
if ! git diff --cached --quiet; then
  git commit -m "init backup repo layout" || true
  git push origin main || log "WARNING: initial push failed (offline?). Will retry on first backup."
fi

# ── 3. Install the backup script ─────────────────────────────────────────────

if [ -f "$SELF_DIR/csld-backup-git.sh" ]; then
  log "Installing backup script → /usr/local/bin/csld-backup-git.sh"
  install -m 0755 "$SELF_DIR/csld-backup-git.sh" /usr/local/bin/csld-backup-git.sh
else
  log "WARNING: $SELF_DIR/csld-backup-git.sh not found."
  log "         You'll need to install it manually to /usr/local/bin/csld-backup-git.sh"
fi

# ── 3b. Provision DATABASE_URL for cron ──────────────────────────────────────
# Cron runs in a clean shell with no env, so DATABASE_URL must be sourced
# from a file. Try to discover it from the running app's environment.

ENV_FILE=/etc/csld-backup.env

if [ -f "$ENV_FILE" ]; then
  log "Existing $ENV_FILE found — leaving it alone (delete the file to regenerate)"
elif [ -n "${DATABASE_URL:-}" ]; then
  log "Writing DATABASE_URL to $ENV_FILE (from current shell)"
  umask 077
  {
    echo "# Generated by csld-backup-setup.sh on $(date -u +%FT%TZ)"
    echo "# Do NOT commit this file to any repo. Owned by root, mode 0600."
    echo "DATABASE_URL='${DATABASE_URL}'"
    if [ -n "${CSLD_DATA_DIR:-}" ]; then
      echo "CSLD_DATA_DIR='${CSLD_DATA_DIR}'"
    fi
  } > "$ENV_FILE"
  chmod 0600 "$ENV_FILE"
else
  log "WARNING: DATABASE_URL not set in this shell and $ENV_FILE doesn't exist."
  log "         You'll need to create $ENV_FILE manually before the cron job can run."
fi

# ── 4. Register cron job ─────────────────────────────────────────────────────

CRON_FILE=/etc/cron.d/csld-backup
CRON_SCHEDULE=${CRON_SCHEDULE:-"0 3 * * *"}  # 03:00 UTC daily

log "Installing cron entry at $CRON_FILE (schedule: $CRON_SCHEDULE)"

cat > "$CRON_FILE" <<EOF
# Daily backup of ČSLD DB + files → private GitHub repo
# Installed by csld-backup-setup.sh on $(date -u +%FT%TZ)
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
$CRON_SCHEDULE root bash -c 'set -a; . /etc/csld-backup.env 2>/dev/null; set +a; exec /usr/local/bin/csld-backup-git.sh' >/var/log/csld-backup.log 2>&1
EOF
chmod 0644 "$CRON_FILE"

# ── 5. Optional first run ─────────────────────────────────────────────────────

if [ "${RUN_BACKUP:-0}" = "1" ]; then
  log "RUN_BACKUP=1 — running first backup now"
  /usr/local/bin/csld-backup-git.sh
else
  log "Skipping first backup (set RUN_BACKUP=1 to run it now, or wait for the cron schedule)."
fi

log "=== Setup complete ==="
log "Next steps:"
log "  1. Verify cron entry:  cat $CRON_FILE"
log "  2. Verify env file:    sudo cat $ENV_FILE"
log "  3. Trigger a test run: sudo RUN_BACKUP=1 $0"
log "  4. Monitor:            tail -f /var/log/csld-backup.log"
log "  5. Restore drill (quarterly): see README in the backup repo"
